apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: openfaas
    meta.helm.sh/release-namespace: openfaas
  creationTimestamp: "2025-12-24T18:25:32Z"
  generation: 1
  labels:
    app: openfaas
    app.kubernetes.io/managed-by: Helm
    chart: openfaas-14.2.132
    component: queue-worker
    heritage: Helm
    release: openfaas
  name: queue-worker
  namespace: openfaas
  resourceVersion: "22893"
  uid: 135cabdb-d312-4810-ab01-2f537f02f394
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: queue-worker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "false"
      labels:
        app: queue-worker
    spec:
      containers:
      - env:
        - name: faas_nats_address
          value: nats.openfaas.svc.cluster.local
        - name: faas_nats_channel
          value: faas-request
        - name: faas_nats_queue_group
          value: faas
        - name: faas_gateway_address
          value: gateway.openfaas.svc.cluster.local
        - name: faas_function_suffix
          value: .openfaas-fn.svc.cluster.local
        - name: ack_wait
          value: 5m
        - name: max_inflight
          value: "1"
        - name: secret_mount_path
          value: /var/secrets/gateway
        - name: basic_auth
          value: "true"
        image: ghcr.io/openfaas/queue-worker:0.14.2
        imagePullPolicy: IfNotPresent
        name: queue-worker
        resources:
          requests:
            cpu: 50m
            memory: 120Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/secrets/gateway
          name: auth
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: auth
        secret:
          defaultMode: 420
          secretName: basic-auth
